---
title: "data"
---

This page does not include replication data for specific papers. For these data, please go to `research`. If you click on a paper of interest, you'll find a button that will direct you to the replication data.

<details>

<summary>[Deshpande, Pia; Hartnett, Brendan; Schaffner, Brian; Ansolabehere, Steve, 2022,<br> "CES 2020 BLM and COVID Data", <https://doi.org/10.7910/DVN/RLO7G9>, Harvard Dataverse, V1]{style="font-size: 1.1em; color: purple; font-weight: normal; display:inline-block"}</summary>

> Supplemental data files for the 2020 Cooperative Congressional Election Study. Datasets include questions on COVID-19 and questions on police brutality and Black Lives Matter. This project was supported by the National Science Foundation, Grant Number SES-1948863.

<!-- Replication Code Button -->

<button onclick="window.open(&#39;https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/RLO7G9&#39;, &#39;_blank&#39;);" style="font-size: 1em; padding: 6px 12px; background-color: white; color: purple; border: 2px solid purple; border-radius: 4px; display: inline-block; margin-top: 20px; margin-left: 10px; text-align: center; transition: background-color 0.3s, color 0.3s;" onmouseover="this.style.backgroundColor=&#39;purple&#39;; this.style.color=&#39;white&#39;;" onmouseout="this.style.backgroundColor=&#39;white&#39;; this.style.color=&#39;purple&#39;;">see data</button>

<!-- BibTeX Citation with Background Color and Extra Space -->

<p style="margin-top: 20px;">

To cite this data using BibTeX, use the following:

</p>

::: {style="background-color: #f0f0f0; padding: 15px; border-radius: 5px; font-family: 'Courier New', monospace; overflow-x: auto;"}
``` bibtex
@data{DVN/RLO7G9_2022,
author = {Deshpande, Pia and Hartnett, Brendan and Schaffner, Brian and Ansolabehere, Steve},
publisher = {Harvard Dataverse},
title = {{CES 2020 BLM and COVID Data}},
year = {2022},
version = {V1},
doi = {10.7910/DVN/RLO7G9},
url = {https://doi.org/10.7910/DVN/RLO7G9}
}
```
:::

</details>

<hr>

<details>

<summary>[Deshpande, Pia; Hershewe, Thomas, 2021,<br>"CES Political Participation 2008-2022", <https://doi.org/10.7910/DVN/JUX8KA>, Harvard Dataverse, V4]{style="font-size: 1.1em; color: purple; font-weight: normal; display:inline-block"}</summary>

> This dataset is a cumulative file of political participation questions in the CES from 2008 to 2022. The initial purpose of this dataset is for use in a tutorial to teach students, though it can be used for other purposes. Pia Deshpande initially created the dataset for years 2008 through 2020. Thomas Hershewe added the year 2022.

<!-- Replication Code Button -->

<button onclick="window.open(&#39;https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/JUX8KA&#39;, &#39;_blank&#39;);" style="font-size: 1em; padding: 6px 12px; background-color: white; color: purple; border: 2px solid purple; border-radius: 4px; display: inline-block; margin-top: 20px; margin-left: 10px; text-align: center; transition: background-color 0.3s, color 0.3s;" onmouseover="this.style.backgroundColor=&#39;purple&#39;; this.style.color=&#39;white&#39;;" onmouseout="this.style.backgroundColor=&#39;white&#39;; this.style.color=&#39;purple&#39;;">see data</button>

<!-- BibTeX Citation with Background Color and Extra Space -->

<p style="margin-top: 20px;">

To cite this data using BibTeX, use the following:

</p>

::: {style="background-color: #f0f0f0; padding: 15px; border-radius: 5px; font-family: 'Courier New', monospace; overflow-x: auto;"}
``` bibtex
@data{DVN/JUX8KA_2021,
author = {Deshpande, Pia and Hershewe, Thomas},
publisher = {Harvard Dataverse},
title = {{CES Political Participation 2008-2022}},
year = {2021},
version = {V4},
doi = {10.7910/DVN/JUX8KA},
url = {https://doi.org/10.7910/DVN/JUX8KA}
}
```
:::

</details>

<hr>

<details>

<summary>[Deshpande, Pia, 2022,<br>"CCES 2020 Supplemental Data", <https://doi.org/10.7910/DVN/6NV9G3>, Harvard Dataverse, V1]{style="font-size: 1.1em; color: purple; font-weight: normal; display:inline-block"}</summary>

> Supplemental data files for the 2020 Cooperative Congressional Election Study. Datasets include the race and ethnicity of congressional candidates.

<!-- Replication Code Button -->

<button onclick="window.open(&#39;https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/6NV9G3&#39;, &#39;_blank&#39;);" style="font-size: 1em; padding: 6px 12px; background-color: white; color: purple; border: 2px solid purple; border-radius: 4px; display: inline-block; margin-top: 20px; margin-left: 10px; text-align: center; transition: background-color 0.3s, color 0.3s;" onmouseover="this.style.backgroundColor=&#39;purple&#39;; this.style.color=&#39;white&#39;;" onmouseout="this.style.backgroundColor=&#39;white&#39;; this.style.color=&#39;purple&#39;;">see data</button>

<!-- BibTeX Citation with Background Color and Extra Space -->

<p style="margin-top: 20px;">

To cite this data using BibTeX, use the following:

</p>

::: {style="background-color: #f0f0f0; padding: 15px; border-radius: 5px; font-family: 'Courier New', monospace; overflow-x: auto;"}
``` bibtex
@data{DVN/6NV9G3_2022,
author = {Deshpande, Pia},
publisher = {Harvard Dataverse},
title = {{CCES 2020 Supplemental Data}},
UNF = {UNF:6:gjKprISuP6j++pufPR7Ncg==},
year = {2022},
version = {V1},
doi = {10.7910/DVN/6NV9G3},
url = {https://doi.org/10.7910/DVN/6NV9G3}
}
```
:::

</details>

<hr>

<details>

<summary>[Deshpande, Pia, 2022,<br>"CCES 2018 Supplemental Data", <https://doi.org/10.7910/DVN/IA9SND>, Harvard Dataverse, V4]{style="font-size: 1.1em; color: purple; font-weight: normal; display:inline-block"}</summary>

> Supplemental data files for the 2018 Cooperative Congressional Election Study. Datasets include the race and ethnicity of congressional candidates.

<!-- Replication Code Button -->

<button onclick="window.open(&#39;https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IA9SND&#39;, &#39;_blank&#39;);" style="font-size: 1em; padding: 6px 12px; background-color: white; color: purple; border: 2px solid purple; border-radius: 4px; display: inline-block; margin-top: 20px; margin-left: 10px; text-align: center; transition: background-color 0.3s, color 0.3s;" onmouseover="this.style.backgroundColor=&#39;purple&#39;; this.style.color=&#39;white&#39;;" onmouseout="this.style.backgroundColor=&#39;white&#39;; this.style.color=&#39;purple&#39;;">see data</button>

<!-- BibTeX Citation with Background Color and Extra Space -->

<p style="margin-top: 20px;">

To cite this data using BibTeX, use the following:

</p>

::: {style="background-color: #f0f0f0; padding: 15px; border-radius: 5px; font-family: 'Courier New', monospace; overflow-x: auto;"}
``` bibtex
data{DVN/IA9SND_2022,
author = {Deshpande, Pia},
publisher = {Harvard Dataverse},
title = {{CCES 2018 Supplemental Data}},
UNF = {UNF:6:s/hg03MO7J1RkXiipXY0MQ==},
year = {2022},
version = {V4},
doi = {10.7910/DVN/IA9SND},
url = {https://doi.org/10.7910/DVN/IA9SND}
}
```
:::

</details>
