---
title: "teaching"
callout: default
callout-icon: false
---

## University of California, Berkeley

<details>

<summary>[[Introduction to Empirical Analysis and Quantitative Methods]{.underline}]{style="font-size: 1.1em; color: purple; font-weight: normal; display: inline-block;"}<br> [Graduate Student Instructor, Spring 2026]{style="font-size: 1.1em; color: purple; font-weight: normal; display: inline-block; margin-left: 20px;"}</summary>

> | **`Instructor: Thad Dunning`**
>
> Held two weekly sections for a total of two hours of instruction time, with an additional two hours of office hours. Helped students complete in-class coding and conceptual assignments. Graded research proposals and provided resources on research designs (e.g. regression discontinuity, differences-in-differences, experiments, and descriptive hypothesis testing). Course topics ranged from basic coding to multivariate regression.

</details>

<details>

<summary>[[Senior Honors Thesis]{.underline}]{style="font-size: 1.1em; color: purple; font-weight: normal; display: inline-block;"}<br> [Statistics and Methods Tutor, Fall 2024 and Spring 2025]{style="font-size: 1.1em; color: purple; font-weight: normal; display: inline-block; margin-left: 20px;"}</summary>

> | **`Instructors: Terri Bimes and Amy Gurowitz`**
>
> I supervised students’ independent honor theses, providing advice on design, analysis, and coding. Each week I had three hours of office hours. I supervised projects using qualitative interviews, text analysis, spatial analysis using geocoding, and survey analysis.

</details>

<details>

<summary>[[Intro to American Politics, UC Berkeley]{.underline}]{style="font-size: 1.1em; color: purple; font-weight: normal; display: inline-block;"}<br> [Graduate Student Instructor, Spring 2024]{style="font-size: 1.1em; color: purple; font-weight: normal; display: inline-block; margin-left: 20px;"}</summary>

> | **`Instructor: Paul Pierson`**
>
> Held two weekly sections for a total of three hours of instruction time with an additional two hours of office hours. Graded assignments like essays and exams and taught students fundamental concepts in American politics. Topics included collective action problems, legislative entrenchment, the history of slavery in the United States, and information asymmetry among voters.

</details>

## Tufts University

<details>

<summary>[[Political Science Research Methods]{.underline}]{style="font-size: 1.1em; color: purple; font-weight: normal; display: inline-block;"}<br> [Teaching Assistant, Spring 2022]{style="font-size: 1.1em; color: purple; font-weight: normal; display: inline-block; margin-left: 20px;"}</summary>

> | **`Instructor: Brian Schaffner`**
>
> Held office hours and review sessions to support students learning R and statistics for political science. Topics included descriptive statistics, regression, experimental design, types of statistical tests, and replication. Led one lecture on the use of RMarkdown, project coding structure, and basic inferential statistics in R.

</details>

<details>

<summary>[[Public Opinion Lab,]{.underline}]{style="font-size: 1.1em; color: purple; font-weight: normal; display: inline-block;"}<br> [Teaching Assistant, Fall 2021 and Spring 2022]{style="font-size: 1.1em; color: purple; font-weight: normal; display: inline-block; margin-left: 20px;"}</summary>

> | **`Instructor: Brian Schaffner`**
>
> Supervised student research, theses, and independent projects on the matter of public opinion. In the spring, led a collaborative lab project on asymmetric polarization and weaponization of the term “critical race theory.”

</details>
